// File generated by Antigravity (manual recreation of DefaultFirebaseOptions)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you are only using iOS and Android for now.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoZX-UqjaqCnqDyzzZcGqUxZQ5acmzfLU',
    appId: '1:568021852039:android:e11e21a429980b24b83d22',
    messagingSenderId: '568021852039',
    projectId: 'beatflow-d1609',
    storageBucket: 'beatflow-d1609.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiFE5hHi2dqrzEHdKc-DPSk5i5KDPb5q0',
    appId: '1:568021852039:ios:01d65c4a86939ee2b83d22',
    messagingSenderId: '568021852039',
    projectId: 'beatflow-d1609',
    storageBucket: 'beatflow-d1609.firebasestorage.app',
    iosBundleId: 'com.isaac.beatflow',
  );
}
